apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-k8s-s2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: my-second-svc
  template:
    metadata:
      labels:
        bb: my-second-svc
    spec:
      containers:
      - name: rust-k8s-s2
        image: dawesc1981/rust-k8s-s2:0.3.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3200
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: rust-k8s-entrypoint-web-s2
  namespace: default
spec:
  type: NodePort
  selector:
    bb: my-second-svc
  ports:
  - port: 3200
    targetPort: 3200
---
apiVersion: v1
kind: Service
metadata:
  name: rust-k8s-entrypoint-svc-s2
  namespace: default
spec:
  type: ClusterIP
  selector:
    bb: my-second-svc
  ports:
  - port: 3201
    targetPort: 3201
