apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-k8s-s1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: my-first-svc
  template:
    metadata:
      labels:
        bb: my-first-svc
    spec:
      containers:
      - name: rust-k8s-s1
        image: dawesc1981/rust-k8s-s1:0.3.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3100
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  name: rust-k8s-entrypoint-web-s1
  namespace: default
spec:
  type: NodePort
  selector:
    bb: my-first-svc
  ports:
  - port: 3100
    targetPort: 3100
---
apiVersion: v1
kind: Service
metadata:
  name: rust-k8s-entrypoint-svc-s1
  namespace: default
spec:
  type: ClusterIP
  selector:
    bb: my-first-svc
  ports:
  - port: 3101
    targetPort: 3101
